name: Build Navigator

on:
  push:
    branches:
      - main
    paths:
      - 'Navigator.py'
      - '.github/**'
      - 'assets/**'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build-macos-intel:
    runs-on: macos-latest
    name: Build Navigator for MacOS (Intel Based)

    steps:
      - name: Download code on MacOS (Intel Based)
        uses: actions/checkout@v3
        with:
          repository: pstlo/Navigator
          ref: main

      - name: Store data in Assets folder
        run: |
          echo "${{ secrets.ENV }}" > "${{ github.workspace }}/Assets/.env"

      - name: Set up Python on MacOS (Intel Based)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install prerequisites on MacOS (Intel Based)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pygame
          pip install cryptography
          pip install pypresence
          pip install python-dotenv

      - name: Build MacOS app
        run: |
          pyinstaller -y --name Navigator --noconsole --add-data Assets:Assets --add-data gameRecords.txt:. -i ".github/Icon.icns" Navigator.py

      - name: Upload MacOS (Intel Based) artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorMacOSIntel
          path: dist/Navigator.app

      - name: Include license and notice in MacOS (Intel Based) artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorMacOSIntel
          path: |
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/NOTICE
