name: Test Build Navigator C

on:
  push:
    branches:
      - main

jobs:
  build-windows-c:
    runs-on: windows-latest
    name: Build Navigator for Windows

    steps:
      - name: Download code on Windows
        uses: actions/checkout@v3
        with:
          repository: pstlo/Navigator
          ref: main

      - name: Store data in Assets folder
        run: |
          echo "${{ secrets.ENV }}" > "${{ github.workspace }}/Assets/.env"

      - name: Set up Python on Windows
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install prerequisites on Windows
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pygame
          pip install cryptography
          pip install pypresence
          pip install python-dotenv

      - name: Build Windows Cython executable
        run: |
            pip install cython
            pip install setuptools
            move ${{ github.workspace }}/.github/Cython ${{ github.workspace }}
            python ${{ github.workspace }}/SetupCython.py build_ext --inplace ${{ github.workspace }}
            pyinstaller --name Navigator --onefile --noconsole --add-data "${{ github.workspace }}/Assets;Assets" -i "${{ github.workspace }}/.github/Icon.ico" --version-file "${{ github.workspace }}/.github/version.txt" "${{ github.workspace }}/Main.py"

      - name: Upload Windows C artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorWindowsC
          path: dist/Navigator.exe

      - name: Include license and notice in Windows C artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorWindowsC
          path: |
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/NOTICE
            ${{ github.workspace }}/gameRecords.txt


