name: Build Navigator

on:
  push:
    branches:
      - main
    paths:
      - 'Navigator.py'

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Navigator for Windows

    steps:
      - name: Download code on Windows
        uses: actions/checkout@v3
        with:
          repository: pstlo/Navigator
          ref: main

      - name: Set up Python on Windows
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install prerequisites on Windows
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pygame
          pip install cryptography

      - name: Create Windows executable
        run: |
            pyinstaller --name NavigatorWindows --onefile --noconsole --add-data "${{ github.workspace }}/Assets;Assets" -i "${{ github.workspace }}\Icon.ico" --version-file "${{ github.workspace }}\version.txt" "${{ github.workspace }}\Navigator.py"

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorWindows
          path: dist/NavigatorWindows.exe

  build-macos-intel:
    runs-on: macos-latest
    name: Build Navigator for MacOS (Intel Based)

    steps:
      - name: Download code on MacOS
        uses: actions/checkout@v3
        with:
          repository: pstlo/Navigator
          ref: main

      - name: Set up Python on MacOS
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install prerequisites on MacOS
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pygame
          pip install cryptography

      - name: Create MacOS App (Intel Based)
        run: |
          pyinstaller --name NavigatorMacOSIntel --noconsole --add-data Assets:Assets -i "Icon.icns" Navigator.py

      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorMacOS
          path: dist/NavigatorMacOSIntel.app

  build-linux:
    runs-on: ubuntu-latest
    name: Build Navigator for Linux

    steps:
      - name: Download code on Linux
        uses: actions/checkout@v3
        with:
          repository: pstlo/Navigator
          ref: main

      - name: Set up Python on Linux
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install prerequisites on Linux
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pygame
          pip install cryptography

      - name: Create Linux executable
        run: |
          pyinstaller --name NavigatorLinux --onefile --noconsole --add-data Assets:Assets Navigator.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: NavigatorLinux
          path: dist/NavigatorLinux
